version: '3.8'

services:

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    depends_on: #dependance explicite
      - db
    #image: wordpress:latest
    build: 
      context: .
      dockerfile: php.dockerfile  # Utilisez le chemin vers votre Dockerfile
    ports:
      - "8080:80" #port d'écoute distinct du port par défaut (80)
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./wordpress:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8181:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  nodejs:
    image: node:latest
    restart: unless-stopped  # Change to unless-stopped for development
    working_dir: /app
    volumes:
      - ./app:/app
    command: ["npm", "install", "-g", "pnpm", "webpack"]

volumes:
  db_data: {}